// The engine writes its worklists RELATIVE TO THE CURRENT DIRECTORY. Run it from the
// repository root — to dogfood, to reproduce a bug, to check a criterion — and it leaves its
// output in the tree beside the source. `.gitignore` already anchored the `verify` half
// (`/VERIFY.md`, `/VERIFY.todo.json`) for exactly that reason; the `adjudicate` half had no
// such entry, so a 2026-08-11 run over two criteria left `ADJUDICATE.md`,
// `ADJUDICATE.todo.json`, `ADJUDICATE.verdicts.json` and `adjudicate/{1.1.1,1.2.1}.md`
// behind, and they were committed and carried for months.
//
// They were harmless — nothing reads them, the Action writes and reads `audits/ADJUDICATE.*`,
// a different path entirely — and that is the point: a stale artefact nobody reads is one
// nobody notices either, and the next reader has to work out whether the repository's own
// audit is a fixture, a baseline, or a mistake.
import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Everything git is tracking at the top level of the repository. */
const trackedAtRoot = (): string[] => execFileSync("git", ["ls-files", "-z", "--", ":(top)*"], { cwd: ROOT, encoding: "utf8" }).split("\0").filter(Boolean);

describe("the repository tracks no artefact one of its own runs left behind", () => {
  // Both worklists, both halves of each: the rendered brief and the machine-readable todo.
  const LEFTOVERS = [/^ADJUDICATE\.(md|todo\.json|verdicts\.json)$/, /^adjudicate\//, /^VERIFY\.(md|todo\.json)$/, /^audits\//, /^\.ultra11y\//];

  // …WITH ONE EXCEPTION, and it is the opposite kind of file rather than a tolerated stray.
  //
  // Everything else this rule catches is OUTPUT: a worklist, a report, a serialized page,
  // regenerated by the next run and read by nobody. The verdict ledger is an INPUT — a claim
  // about this codebase, one entry per adjudicated criterion with its justification, its
  // citations and a fingerprint of the evidence it was ruled against — and the `ledger-gate`
  // job in ci.yml replays it on every push to hold the RGAA grid to 106/106 with no model in
  // the loop. Deleting it would not tidy the repository, it would remove the gate.
  const LEDGER = ".ultra11y/verdicts/rgaa.json";

  it("has none of them in the index", () => {
    const offenders = trackedAtRoot().filter((f) => LEFTOVERS.some((re) => re.test(f)) && f !== LEDGER);
    expect(offenders, "a run's output is tracked — delete it and anchor it in .gitignore").toEqual([]);
  });

  // And the exception is pinned from the other side, because a gate whose input quietly
  // disappeared would be worse than no gate: `verify --apply` on a missing ledger fails loudly
  // in CI, but nothing here would have said WHY, and the obvious repair — dropping the job —
  // is the wrong one.
  it("tracks the verdict ledger, which is a reviewed claim and not a leftover", () => {
    expect(trackedAtRoot()).toContain(LEDGER);
  });

  // THE OTHER KIND OF STRAY, and the rule above could not see it: not a run's output, but a
  // human's scratch file swept in by `git add -A`.
  //
  // Written from experience rather than from principle — `zz-watch.sh`, a throwaway loop that
  // polled a CI run, rode three commits to `main` that way. It never reached the npm tarball
  // (`package.json` `files` is an allowlist), so nothing downstream broke and nothing failed;
  // it simply sat in the repository looking as if somebody meant it. That is precisely the
  // failure mode this file exists for: harmless, invisible, and permanent.
  //
  // Anchored on the SHAPE of a scratch name rather than on a list of extensions, because the
  // next one will not be called zz-watch.sh. A root-level script or note whose name starts
  // `zz`, `tmp`, `scratch`, `wip` or `debug` is not a deliverable; if one ever legitimately is,
  // it wants a real name, and that is the point of the rule.
  const SCRATCH = /^(zz|tmp|temp|scratch|wip|debug|test-|foo|bar)[.\-_a-z0-9]*\.(sh|mjs|cjs|js|ts|json|txt|md|log)$/i;

  it("has no scratch file at its root", () => {
    const offenders = trackedAtRoot().filter((f) => !f.includes("/") && SCRATCH.test(f));
    expect(offenders, "a scratch file is tracked — `git add -A` swept it in; delete it").toEqual([]);
  });

  it("keeps that ledger readable and non-empty, since a gate replays it", () => {
    const j = JSON.parse(readFileSync(join(ROOT, LEDGER), "utf8"));
    expect(j.standard).toBe("rgaa");
    expect(Array.isArray(j.entries) ? j.entries.length : Object.keys(j.entries ?? {}).length).toBeGreaterThan(0);
  });

  // The index being clean today is a state; the ignore rule is what keeps it one. Anchored
  // with a leading slash so it cannot shadow `skills/…/references/verify.md` on a
  // case-insensitive filesystem — the reason the VERIFY entries are written that way.
  it.each([
    "/ADJUDICATE.md",
    "/ADJUDICATE.todo.json",
    "/ADJUDICATE.verdicts.json",
    "/adjudicate/",
    "/VERIFY.md",
    "/VERIFY.todo.json",
  ])("anchors %s in .gitignore", (entry) => {
    const lines = readFileSync(join(ROOT, ".gitignore"), "utf8")
      .split("\n")
      .map((l) => l.trim());
    expect(lines).toContain(entry);
  });
});

// Two properties every workflow in this repository has to hold, and neither is visible when
// you read one file at a time.
describe("every workflow states its blast radius and its ceiling", () => {
  const DIR = join(ROOT, ".github/workflows");
  const files = readdirSync(DIR).filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"));
  const workflows = files.map(
    (f) =>
      [
        f,
        parse(readFileSync(join(DIR, f), "utf8")) as {
          permissions?: unknown;
          on?: { workflow_dispatch?: { inputs?: Record<string, { default?: unknown; type?: string }> } };
          // A number, or a `${{ inputs.x }}` expression — see the ceiling test below.
          jobs: Record<string, { permissions?: unknown; "timeout-minutes"?: number | string }>;
        },
      ] as const,
  );

  it("has workflows to check at all", () => {
    expect(files.length).toBeGreaterThan(0);
  });

  // A workflow that declares none inherits the REPOSITORY default, which is a setting in a
  // web UI rather than a fact in the diff — and it is read/write on any repository that never
  // narrowed it. ci.yml was the one that did, for a run that needs nothing but the checkout.
  it.each(workflows)("%s declares permissions, at the workflow or on every job", (_name, wf) => {
    const declared = wf.permissions !== undefined || Object.values(wf.jobs ?? {}).every((j) => j.permissions !== undefined);
    expect(declared).toBe(true);
  });

  // MEASURED, the expensive way: `type: number` was declared on a workflow_dispatch input,
  // every YAML parser accepted it, and GitHub rejected the whole workflow at DISPATCH time —
  // no jobs, no log, a two-second failure. The keyed adjudication was undispatchable for as
  // long as it took to notice.
  //
  // workflow_dispatch takes `string` (the default), `choice`, `boolean` and `environment`,
  // and nothing else — `number` belongs to workflow_call, which is the trap. A number is
  // passed as a string and read with `fromJSON`.
  it.each(workflows)("%s declares only input types workflow_dispatch accepts", (_name, wf) => {
    const DISPATCH_INPUT_TYPES = ["string", "choice", "boolean", "environment"];
    for (const [id, spec] of Object.entries(wf.on?.workflow_dispatch?.inputs ?? {})) {
      if (spec.type === undefined) continue; // omitted means string
      expect(DISPATCH_INPUT_TYPES, `input \`${id}\` declares type \`${spec.type}\``).toContain(spec.type);
    }
  });

  // GitHub's default ceiling is six hours. Measured on this repository: an install step wedged
  // on a network flake ran for 3h27 before anyone looked, and read in the run list exactly
  // like a code failure. `ee6625e` said "every job now carries a timeout-minutes"; five did
  // not, including the one that pushes to main and publishes to npm.
  it.each(workflows)("%s gives every job a timeout", (_name, wf) => {
    // A literal number, or an expression reading a dispatch input that ITSELF defaults to a
    // number. The second form is what lets a hand-dispatched run raise its own ceiling; it is
    // only a real ceiling if the default is one, so the input is followed rather than trusted.
    const positive = (v: unknown): boolean => Number(v) > 0 && Number.isFinite(Number(v));
    const bounded = (v: unknown): boolean => {
      if (typeof v === "number") return v > 0;
      if (typeof v !== "string") return false;
      // `${{ inputs.x }}` or `${{ fromJSON(inputs.x) }}` — the second is what a dispatch
      // input needs, since every one of them arrives as a STRING (see the type test below).
      const m = v.match(/^\$\{\{\s*(?:fromJSON\()?\s*inputs\.([A-Za-z0-9_-]+)\s*\)?\s*\}\}$/);
      if (!m) return false;
      return positive(wf.on?.workflow_dispatch?.inputs?.[m[1]!]?.default);
    };
    const naked = Object.entries(wf.jobs ?? {})
      .filter(([, j]) => !bounded(j["timeout-minutes"]))
      .map(([id]) => id);
    expect(naked, "these jobs run against GitHub's six-hour default").toEqual([]);
  });
});
